name = 'Otávio Carvalho Blog Theme'
license = 'MIT'
licenselink = 'https://github.com/otaviocarvalho/otavio.cat/LICENSE'
description = 'Otávio Carvalho personal blog theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/otaviocarvalho/otavio.cat'

# Taxonomy terms
tags = ['blog', 'personal']
features = ['blog', 'rss', 'webpage']

# If the theme has a single author
[author]
  name = 'Otávio Carvalho'
  homepage = 'https://otavio.cat'
